language: elixir
sudo: false
elixir: 1.7.3
otp_release: 21.1
notifications:
  recipients:
    - office@nerdslabs.co
script:
  - if [[ `elixir -v` = *"1.6"* ]]; then mix format --check-formatted; fi
  - mix test
# after_script:
#   - mix deps.get --only docs
#   - MIX_ENV=docs mix inch.report