language: elixir
sudo: false
elixir: 1.6.6
otp_release: 20.1
matrix:
  include:
    - elixir: 1.4.0
      otp_release: 19.1
notifications:
  recipients:
    - office@nerdslabs.co
script:
  - if [[ `elixir -v` = *"1.6"* ]]; then mix format --check-formatted; fi
  - mix test
# after_script:
#   - mix deps.get --only docs
#   - MIX_ENV=docs mix inch.report